spring:
  datasource:
    url: jdbc:mysql://192.168.45.194:13306/night-saver?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

sub:
  server:
    night-saver-image-server:
      host: http://192.168.45.194:55003
    night-saver-web:
      host: https://night-saver.sggnology.com

springdoc:
  swagger-ui:
    enabled: false

auth:
  jwt:
    access-token:
      secret-key: gkdnfdlrnldudnjwlsWksjehdkfwlabc
      expire-seconds: 86400000 # 24 hours
    refresh-token:
      secret-key: gkdnfdlrnldudnjwlsWksjehdkfwlcba
      expire-seconds: 2592000000 # 30 days