spring:
  datasource:
    url: jdbc:mysql://192.168.45.194:13306/night-saver?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    properties:
#      hibernate:
#        format_sql: true

sub:
  server:
    night-saver-image-server:
      host: http://192.168.45.194:55003
    night-saver-web:
      host: http://localhost:3000

auth:
  jwt:
    secret-key: gkdnfdlrnldudnjwlsWksjehdkfwlabc
    expire-seconds: 3600000

#logging:
#  level:
#    org.hibernate.SQL: debug
#    org.hibernate.orm.jdbc.bind: trace
